---
# Orchestration refers to the management of many automated tasks

  - name: "Orchestration Example"
    #hosts: logicservers
    hosts: all
    serial: 1

    tasks:
      - name: "Shutdown Server"
        debug:
          msg: "Shutdown {{ inventory_hostname }}"

      - name: "Upgrade Server Firmware "
        debug:
          msg: "Upgrade {{ inventory_hostname }}"

      - name: " Restarting Server"
        debug:
          msg: " Start {{ inventory_hostname }}"

      - name: "Verifying  Server is up & Running"
        debug:
          msg: "Verify {{ inventory_hostname }}"  