FROM python:3

RUN pip install --upgrade pip

WORKDIR /hello_Jldroid25

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .
# Run gunicorn , bind it to 0.0.0.0:8080, inside our app
CMD  ["gunicorn", "-b", "0.0.0.0:8000", "hello:app"]