FROM nginx:1.19.7-alpine
# add the package .JSON in our app dir | The Caching
ADD package*.json ./
# Add everything in this current dir to conatainer dest. /usr/share/nginx/html
ADD . /usr/share/nginx/html